name: Automation Web Testing with Ruby x Cucumber
on: [push, pull_request]
jobs: 
  build: 
   runs-on: ubuntu-latest
   steps: 
- uses:actions/checkout@v3
  - name: Setup ruby
    uses: ruby/setup-ruby@v1
    with: 
      ruby-version: 3.1.4
      
  - name: Chrome Install
    uses: browser-actions/setup-chrome@latest
    with: 
      chrome-version: stable

  - name: Chromedriver Install
    run: |
      wget "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip"
      unzip chromedriver_linux64.zip 
      sudo mv chromedriver /usr/bin/

  - name: Bundle Insalll
    run: bundle insatll

  - name: Run Cucumber Test
    run: | 
      chrome --version
      chromedriver --version

      HEADLESS=true bundle exec cucumbera

  
